#!/bin/bash
# Builds xinput_fix.c for 64-bit and 32-bit Windows and regenerates Sources/HubCore/XInputFixDLLs.swift.
#   ZIG=/path/to/zig ./Support/xinput-fix/build.sh
set -euo pipefail
cd "$(dirname "$0")"
ZIG="${ZIG:-zig}"
OUT="$(mktemp -d)"
trap 'rm -rf "$OUT"' EXIT

exports=(XInputGetState XInputSetState XInputGetCapabilities XInputEnable XInputGetBatteryInformation
         XInputGetKeystroke XInputGetDSoundAudioDeviceGuids XInputGetAudioDeviceIds)
ordinals=("XInputGetStateEx 100 8" "XInputWaitForGuideButton 101 12" "XInputCancelGuideButtonWait 102 4"
          "XInputPowerOffController 103 4" "XInputGetBaseBusInformation 104 8" "XInputGetCapabilitiesEx 108 16")
# Argument bytes of each export, for the 32-bit stdcall names (bash 3.2 has no associative arrays).
stack() {
  case "$1" in
    XInputEnable) echo 4 ;;
    XInputGetState|XInputSetState) echo 8 ;;
    XInputGetAudioDeviceIds) echo 20 ;;
    *) echo 12 ;;
  esac
}

for target in x86_64 x86; do
  def="$OUT/$target.def"
  { echo "LIBRARY xinput1_4"; echo "EXPORTS"
    for name in "${exports[@]}"; do
      if [ "$target" = x86 ]; then echo "  $name=$name@$(stack "$name")"; else echo "  $name"; fi
    done
    for entry in "${ordinals[@]}"; do
      read -r name ord bytes <<<"$entry"
      if [ "$target" = x86 ]; then echo "  $name=$name@$bytes @$ord NONAME"; else echo "  $name @$ord NONAME"; fi
    done; } > "$def"
  "$ZIG" cc -target "$target-windows-gnu" -shared -O2 -s -o "$OUT/$target.dll" xinput_fix.c "$def"
done

swift="../../Sources/HubCore/XInputFixDLLs.swift"
{
  echo "// Generated by Support/xinput-fix/build.sh from xinput_fix.c — do not edit."
  echo "import Foundation"
  echo ""
  echo "enum XInputFixDLLs {"
  echo "    static let x64 = Data(base64Encoded: \"$(base64 -i "$OUT/x86_64.dll" | tr -d '\n')\")!"
  echo "    static let x86 = Data(base64Encoded: \"$(base64 -i "$OUT/x86.dll" | tr -d '\n')\")!"
  echo "}"
} > "$swift"
ls -la "$OUT"/*.dll
echo "wrote $swift"
